### ISSUE TITLE
import dll error

### ISSUE THREAD

**Issue by muhsindemir** [dilshan/zfm20-lib#1]
He Dilshan,

Hope everything is alright for you, I try to use your lib but the dllimport code does not work.

 [DllImport("Zfm.dll", EntryPoint = "ZfmInitialize", CallingConvention = CallingConvention.Cdecl)]

Cant find the  "Zfm.dll" could you please tell me about it

**Comment by dilshan** [comment]
Hi,


Did you place zfm.dll in same directory where your executable resides?


Also check you are using correct DLL with your build architecture (e.g: x86 version of DLL with Win32 - x86 build, etc.)

________________________________

**Comment by dilshan** [comment]
Close issue due to no response.
