### ISSUE TITLE
Using USB Interface instead of UART

### ISSUE THREAD

**Issue by TehseenHasan** [dilshan/zfm20-lib#2]
I want to download scanned fingerprint image using **USB interface** instead of UART because UART communication takes about 4 to 5 seconds to save Image on PC... So I want to use USB interface directly... How can I do this... ?

**Comment by dilshan** [comment]
ZFM20 comes with UART endpoint. There are few options you can try:

- Decrease communication delay by modifying lib source code.
- Communicate directly with sensor through MCU and then transfer captured image through high-speed bus.

Please note that this zfm20-lib is not optimized for speed, there are several ways to optimize speed of this lib.

**Comment by TehseenHasan** [comment]
Okay. Thanks.

**Comment by jastabud** [comment]
how can i download the zfm20lib.dll?  
in fingerprint in UArt .

**Comment by TehseenHasan** [comment]
I found the SDK links for R30X series Fingerprint Sensors... maybe it will work for ZFM sensors too... you should try TestDemo.exe software from this link....

https://github.com/bastianraschke/pyfingerprint/issues/52#issuecomment-451870524

**Comment by TehseenHasan** [comment]
This is a C# program to communicate with R30x Fingerprint sensor with **USB protocol**... This example downloads scanned fingerprint image from Sensor to our Computer.... 
https://github.com/TehseenHasan/R305_fingerprint_sensor_usb_interface

Understand the different functions of **SynoAPIEx.dll** file from this example if you want to use this same as pyFingerprint library...
